### ISSUE TITLE
DataChangeTrackService could not be converted to string

### ISSUE THREAD

**Issue by KINKCreative** [symbiote/silverstripe-datachange-tracker#5]
I am tracking a Varchar and a Boolean.

```
Subsite:
  significant_fields:
   - MyVarcharField
   - MyBooleanField
  extensions:
   - ChangeRecordable
   - SignificantChangeRecordable
```

I see the list of change records, but clicking to view details, I receive this error:

```
Object of class DataChangeTrackService could not be converted to string...
```

https://www.dropbox.com/s/6wh82awrq7iurze/Screenshot%202015-11-22%2010.45.06.png?dl=0

Should there be a callback for non-text fields? or is it a Casting or forTemplate issue?
